[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/icarojobs/orderflow-rs"
authors = ["Icaro William <icarojobsoficial@gmail.com>"]

[workspace.dependencies]
orderflow-engine = { path = "crates/engine" }
orderflow-events = { path = "crates/events" }
orderflow-proto = { path = "crates/proto" }
orderflow-telemetry = { path = "crates/telemetry" }
prost = "0.14"
protoc-bin-vendored = "3"
tonic = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support", "plotters"] }
proptest = "1"
slab = "0.4"
anyhow = "1"
axum = "0.8"
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.18", default-features = false }
futures-util = "0.3"
rskafka = { version = "0.6", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "net", "time", "io-util"] }
tokio-stream = { version = "0.1", features = ["sync", "net"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
thiserror = "2"

[profile.release]
lto = "thin"
codegen-units = 1
debug = "line-tables-only"

[profile.bench]
inherits = "release"
